---
build-by-default: true
branches:
- master
projects:
  QuickFriends:
    path: ""
    libs:
      - src: Swift-Strider/Remark/Remark
        version: ^1.2.1
        epitope: .random
      - src: poggit/libasynql/libasynql
        version: ^4.0
        epitope: .random
      - src: sof3/await-generator/await-generator
        version: ^3.4
        epitope: .random
...
