name: QuickFriends
author: DiamondStrider1

main: DiamondStrider1\QuickFriends\Main
version: 1.0.0
api: 4.0.0

permissions:
  quickfriends.command.friend:
    default: true
  quickfriends.command.friend.add:
    default: true
  quickfriends.command.friend.remove:
    default: true
  quickfriends.command.friend.list:
    default: true
  quickfriends.command.friend.join:
    default: true
  quickfriends.command.block:
    default: true
  quickfriends.command.block.add:
    default: true
  quickfriends.command.block.remove:
    default: true
  quickfriends.command.block.list:
    default: true
