language:
  default-language: en_US

user-interface:
  notify-friend-join: true
  notify-friend-quit: true

social:
  # Time in seconds before a friend request expires.
  friend-request-duration: 60
  # This can be bypassed with the permission:
  # quickfriends.bypass.friend-limit
  max-friend-limit: 10

  # Worlds where a player may /f join to
  # teleport to their friend.
  joinable-worlds:
    # true=allow-list, false=block-list
    enable-block-list: false
    # worlds to allow or block
    worlds:
      - world
      - lobby

preferences:
  # Every user has their own preference settings,
  # the default preferences are given to new players.
  default-preferences:
    # Wether to disable forms
    prefers-text: false
    # May be "everyone", "friends", or "nobody"
    os-visibility: everyone
    mute-friend-requests: false

database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1
  # Wether to log debugging messages of database calls.
  enable-logging: false
