<?php

declare(strict_types=1);

namespace DiamondStrider1\QuickFriends\Language;

/**
 * This class was auto-generated by
 * `tools/language/generate-language.php`.
 */
final class LanguageInfo
{
    public const ALL_LANGS = [
        'en_US' => true,
    ];
}
